---
- import_playbook: infra-badger-prod.yml

- name: Set up director node in the infra project, badger network, and rod tier
  hosts: infra-badger-prod-director
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  roles:
    - director
...
