---
- import_playbook: infra-badger-prod.yml

- name: Set up Artifactory in the infra project, badger network, and prod tier
  hosts: infra-badger-prod-artifactory
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  roles:
    - teaming
    - nginx
    - postgresql
    - artifactory
...

